df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("bangalore rural","Bangalore"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("bangalor","Bangalore"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("bangaluru","Bangalore"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("nelamangala bangalore rural","Bangalore"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("jayanagar bangalore","Bangalore"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("bangaloure","Bangalore"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Bangaore","Bangalore"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Banglalore","Bangalore"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("bangalore hoskote","Bangalore"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("bengaluru","Bangalore"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("bengalore","Bangalore"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("bengulore","Bangalore"))


df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Hyderabad","Hyderabad"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Hyderbad","Hyderabad"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Hydrabad","Hyderabad"))
# df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Hyd$","Hyderabad"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Hydereabad","Hyderabad"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Hyderabad East","Hyderabad"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Hyderabad Local","Hyderabad"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Medchal, Hyderabad","Hyderabad"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Hydrebad","Hyderabad"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("hyderabd","Hyderabad"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Hydarabad","Hyderabad"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Hyderabaf","Hyderabad"))

df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Mumbai","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Navi Mumbai","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Navimumbai","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Andheri.,Mumbai","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Mumbai thane","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Mumbai City","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Belapur Navi Mumbai","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("West Mumbai","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Juinagar Navi Mumbai","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Mumbai (E)","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Kharghar navimumbai","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Mumbai goregaon west","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Andheri mumbai","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Bandra, mumbai","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Nerul Navi Mumbai","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Koper Khairane Navi Mumbai","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("New mumbai ghansoli","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Mahim mumbai","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Airoli, Navi mumbai","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("malad West mumbai","Mumbai"))


df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Pune","Pune"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Pune Maharashtra","Pune"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Chakan, Pune","Pune"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Khadki pune","Pune"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("pune city","Pune"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Kharadi Pune","Pune"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Pune pimpri chinchwad","Pune"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Nigdi pune","Pune"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Pimpri Chinchwad pune","Pune"))

df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Thane","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Thane West","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Kalyan dist. Thane","Mumbai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Mumbai thane","Mumbai"))


df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Chennai","Chennai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Chennai,","Chennai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("perungudi,chennai","Chennai"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Chennai -","Chennai"))

df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("K.V.Rangareddy","Ranga Reddy"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Rangareddy","Ranga Reddy"))

df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Vishakapatnam","Visakhapatnam"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Vishakha pantanm","Visakhapatnam"))

df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Kolkata","Kolkata"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("kolkkata","Kolkata"))


df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("South Delhi","Delhi"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("South West Delhi","Delhi"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("West Delhi","Delhi"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("East Delhi","Delhi"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("North West Delhi","Delhi"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Central Delhi","Delhi"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("New Delhi","Delhi"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("North Delhi","Delhi"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Delhi","Delhi"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("North East Delhi","Delhi"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Newdelhi","Delhi"))

df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Gurugram","Gurugram"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Gururgram","Gurugram"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Gurgoan","Gurugram"))
df["Residence City"] = df["Residence City"].apply(lambda x: str(x).replace("Gurgram","Gurugram"))
